import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import { ModalProvider } from "@/providers/modal-provider";
import { ToasterProvider } from "@/providers/toast-proivder";
// import prismadb from "@/lib/prismadb";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin dashboard",
  description: "Generated by reem ebrahim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const store =prismadb.store
  return (
    <ClerkProvider
    // appearance={{
    //   baseTheme: dark
    // }}
  >
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider/>
        <ModalProvider/>
        {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
